;;; gen-large.el --- Generate reproducible table fixtures -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Commentary:
;; Run: Emacs -Q --batch -l demos/gen-large.el -f org-table-widget-demo-generate
;;; Code:
(require 'cl-lib)

(defconst org-table-widget-demo--directory
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory containing demo fixtures.")

(defun org-table-widget-demo-generate ()
  "Generate 500-by-8 and 3000-by-6 data tables beside this script."
  (interactive)
  (dolist (spec '(("large.org" 500 8) ("huge.org" 3000 6)))
    (pcase-let ((`(,name ,rows ,columns) spec))
      (with-temp-file (expand-file-name name org-table-widget-demo--directory)
        (insert (format "#+title: %d rows by %d columns\n" rows columns)
                "# Generated by gen-large.el; check reflow, scrolling, and latency.\n\n")
        (insert "| " (mapconcat (lambda (n) (format "Field %d" n))
                                (number-sequence 1 columns) " | ") " |\n")
        (insert "|" (mapconcat #'identity (make-list columns "---------") "+") "|\n")
        (dotimes (row rows)
          (insert "| "
                  (mapconcat
                   (lambda (column)
                     (cond
                      ((= column 0) (format "id-%04d" (1+ row)))
                      ((and (= column 2) (= (% row 47) 0))
                       (format "长说明 %d: %s" row
                               (mapconcat #'identity
                                          (make-list 12 "中文 English 日本語 한국어") " ")))
                      (t (format "%s %d/%d"
                                 (nth (% (+ row column) 4)
                                      '("中文" "English" "日本語" "한국어"))
                                 (1+ row) (1+ column)))))
                   (number-sequence 0 (1- columns)) " | ") " |\n"))))))

(provide 'org-table-widget-demo-generator)
;;; gen-large.el ends here
